---
env: lfc                  # Short name of the environment (sbx, stg or prd)
component: db            # Component name, should be equal to component name in Codefresh pipeline and name of this yml file.
componentType: migrations     # Component (server, cron, migrations, etc)

ports:
  - name: tcp
    protocol: TCP
    servicePort: 80
    containerPort: 8080
    appProtocol: http

serviceAccount:
  create: false
  name: "default"

service:
  enabled: true

ingress:
  port: 80

deployment:
  customNodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: eks.amazonaws.com/capacityType
            operator: In
            values:
              - SPOT

  replicaCount: 1

  terminationGracePeriodSeconds: 300
  # Resource limits can be tuned according to particular application requirements
  # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  readinessProbe:
    periodSeconds: 10
    failureThreshold: 30
    tcpSocket:
      port: 5432

  livenessProbe:
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    tcpSocket:
      port: 5432

  lifecycle:
    preStop:
      exec:
        command: ["/bin/sh", "-c", "sleep 120"]

pvc:
  enabled: true
  size: 1Gi
  storageClassName: ebs-sc
  accessMode: ReadWriteOnce
  volumeMode: Filesystem
  annotations:
